# Import Libraries

In [1]:
import numpy as np

# Numpy Array

## Diamention Based

### 1D array

In [2]:
list = [1,2,3]
list

[1, 2, 3]

In [3]:
np_list = np.array(list)
np_list

array([1, 2, 3])

### 2D array

In [4]:
list2 = [
    [1, 2, 3],
    [4, 5, 6]
]
np_2d_list = np.array(list2)
np_2d_list

array([[1, 2, 3],
       [4, 5, 6]])

# Making np Array based on different conditions

## Based on Start, End, Increament

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## Zeros matrix

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## Ones matrix

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Eye matrix

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

## Evenly distributed matrix based on start, stop, #elements

In [12]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## Random Matrix

In [14]:
np.random.rand(5,5)

array([[0.39404757, 0.42226827, 0.22994663, 0.76780813, 0.09490508],
       [0.32146419, 0.64628545, 0.35046703, 0.40193774, 0.4192061 ],
       [0.20025   , 0.28452442, 0.2971855 , 0.28054753, 0.76000767],
       [0.36664756, 0.43834124, 0.12585739, 0.42290709, 0.29965288],
       [0.86742237, 0.69679189, 0.15419646, 0.51060996, 0.96534852]])

In [18]:
np.random.randint(0,10, 4)

array([7, 4, 0, 5])

In [19]:
np.random.randint(0,10, (4,4))

array([[8, 9, 0, 7],
       [0, 6, 5, 1],
       [2, 6, 1, 8],
       [1, 2, 1, 6]])

# Operation

In [25]:
l = np.random.randint(1,11, 5)
l

array([1, 3, 9, 5, 9])

## Get Max, Min

In [26]:
l.max()

9

In [27]:
l.min()

1

## Get Index of Max, Min

In [28]:
l.argmax()

2

In [29]:
l.argmin()

0

## Slicing

In [31]:
l

array([1, 3, 9, 5, 9])

In [30]:
l[1:]

array([3, 9, 5, 9])

In [32]:
l[::-1]

array([9, 5, 9, 3, 1])

In [36]:
l

array([1, 3, 9, 5, 9])

In [40]:
l[0:-1: 2]

array([1, 9])