# Import Libraries

In [1]:
import numpy as np

# Numpy Array

## Diamention Based

### 1D array

In [2]:
list = [1,2,3]
list

[1, 2, 3]

In [3]:
np_list = np.array(list)
np_list

array([1, 2, 3])

### 2D array

In [4]:
list2 = [
    [1, 2, 3],
    [4, 5, 6]
]
np_2d_list = np.array(list2)
np_2d_list

array([[1, 2, 3],
       [4, 5, 6]])

# Making np Array based on different conditions

## Based on Start, End, Increament

In [5]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

## Zeros matrix

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## Ones matrix

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Eye matrix

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

## Evenly distributed matrix based on start, stop, #elements

In [12]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [13]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## Random Matrix

In [14]:
np.random.rand(5,5)

array([[0.96006317, 0.10424614, 0.2922639 , 0.21978753, 0.53663132],
       [0.0347911 , 0.73980852, 0.11955085, 0.56546006, 0.83922683],
       [0.24451565, 0.31434971, 0.75851284, 0.60286223, 0.10267877],
       [0.29191079, 0.55567775, 0.89595135, 0.62609059, 0.86686527],
       [0.38338322, 0.76651686, 0.73219574, 0.13348045, 0.03762427]])

In [15]:
np.random.randint(0,10, 4)

array([3, 1, 4, 1])

In [16]:
np.random.randint(0,10, (4,4))

array([[7, 6, 1, 9],
       [6, 3, 8, 1],
       [1, 8, 6, 9],
       [8, 4, 5, 2]])

# Operation

In [17]:
l = np.random.randint(1,11, 5)
l

array([10,  8,  6,  8,  2])

## Get Max, Min

In [18]:
l.max()

10

In [19]:
l.min()

2

## Get Index of Max, Min

In [20]:
l.argmax()

0

In [21]:
l.argmin()

4

## Slicing

In [22]:
l

array([10,  8,  6,  8,  2])

In [23]:
l[1:]

array([8, 6, 8, 2])

In [24]:
l[::-1]

array([ 2,  8,  6,  8, 10])

In [25]:
l

array([10,  8,  6,  8,  2])

In [26]:
l[0:-1: 2]

array([10,  6])

## Condition

In [27]:
l

array([10,  8,  6,  8,  2])

In [28]:
l>2

array([ True,  True,  True,  True, False])

In [29]:
l[l>2]

array([10,  8,  6,  8])

In [33]:
l[(l>2)&(l%2==0)]

array([10,  8,  6,  8])