# Import Libraries

In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'1.11.0'

# Create Different Types of Tensors

## Numpy Array to Tensor

In [3]:
np_arr = np.arange(0,6)
np_arr

array([0, 1, 2, 3, 4, 5])

In [4]:
np_arr.dtype

dtype('int64')

In [5]:
type(np_arr)

numpy.ndarray

In [6]:
torch_arr = torch.from_numpy(np_arr)
torch_arr

tensor([0, 1, 2, 3, 4, 5])

In [7]:
torch_arr.dtype

torch.int64

In [8]:
type(torch_arr)

torch.Tensor

In [9]:
np_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
my_tensor_arr1 = torch.from_numpy(np_arr)
my_tensor_arr2 = torch.tensor(np_arr)

In [11]:
my_tensor_arr1

tensor([0, 1, 2, 3, 4, 5])

In [12]:
my_tensor_arr2

tensor([0, 1, 2, 3, 4, 5])

In [13]:
np_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
np_arr[0] = 100
np_arr

array([100,   1,   2,   3,   4,   5])

In [15]:
my_tensor_arr1

tensor([100,   1,   2,   3,   4,   5])

In [16]:
my_tensor_arr2

tensor([0, 1, 2, 3, 4, 5])

## Empty Tensor

In [17]:
torch.empty(4,2)

tensor([[ 0.0000e+00, -1.0842e-19],
        [-7.4942e+35, -1.0845e-19],
        [ 7.9605e+14,  4.5894e-41],
        [ 7.9460e+14,  4.5894e-41]])

## Zero Tensor

In [18]:
torch.zeros(4,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [19]:
# integer tensor
torch.zeros(4,2, dtype = torch.int64)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

## Ones Tensor

In [20]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
torch.ones(4,3, dtype=torch.int64)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

## Tensor From Range

In [22]:
torch.arange(1, 11, 1)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
torch.arange(1, 11, 1).reshape(2,5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

## Using linespace

In [24]:
torch.linspace(1, 10, 10, dtype=torch.int8)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=torch.int8)

In [25]:
torch.linspace(1, 10, 10, dtype=torch.int8).reshape(2,5)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]], dtype=torch.int8)

## From List to tensor

In [26]:
torch.tensor([1, 3, 5])

tensor([1, 3, 5])

## Using Random Number

In [37]:
torch.rand(4,3)

tensor([[0.5376, 0.8489, 0.4192],
        [0.3997, 0.7177, 0.8469],
        [0.5184, 0.5354, 0.7301],
        [0.7548, 0.9646, 0.4403]])

In [41]:
# mean 0, std 1
torch.randn(4,3)

tensor([[ 0.5720, -0.2174, -0.0274],
        [-1.4308,  1.2592, -0.1028],
        [-0.2325,  2.6576,  0.4156],
        [ 0.3033,  1.9944, -0.0311]])

In [42]:
torch.randint(low=0, high=11, size=(2,5))

tensor([[ 3,  9,  1,  4,  7],
        [10, 10,  8,  8,  1]])

##  Same Shape of a tensor

In [54]:
a = torch.tensor([
        [1, 3],
        [2, 5], 
        [8, 0]
    ])
a

tensor([[1, 3],
        [2, 5],
        [8, 0]])

In [60]:
b = torch.rand_like(a, dtype=torch.float)
b

tensor([[0.6035, 0.0988],
        [0.5131, 0.1624],
        [0.6838, 0.5290]])

In [58]:
b.dtype

torch.float32

# Tensor Operations

## Change Data Type 

In [28]:
initial_tensor = torch.arange(1, 11, 1).reshape(2,5)
initial_tensor

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [29]:
initial_tensor.dtype

torch.int64

In [32]:
# convert it from int64 to int8

In [35]:
initial_tensor = initial_tensor.type(torch.int8)
initial_tensor

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]], dtype=torch.int8)

In [36]:
initial_tensor.dtype

torch.int8

## Manual Seed

In [61]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

## Slicing Tensor

In [64]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [68]:
# get value from row 2, column 0 => 4
x[2,0]

tensor(4)

In [69]:
# get all the values of column 1
x[:,1]

tensor([1, 3, 5])

In [74]:
# Slicing the values of column0
x[:, 0:1]

tensor([[0],
        [2],
        [4]])